name: LOC Tracker

on:
  push:
    branches:
      - main
  workflow_dispatch: # To trigger manually
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight

jobs:
  track-loc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Required Tools
        run: sudo apt-get install cloc

      - name: Generate LOC Report
        run: |
          # Initialize the report file with headers
          echo "Date,Added,Deleted,Net Change" > loc_report.csv

          # Get the first commit date (starting point)
          first_commit_date=$(git log --reverse --pretty=format:%as | head -n 1)
          current_date=$(date +%Y-%m-%d)

          echo "First Commit Date: $first_commit_date"
          echo "Current Date: $current_date"

          # Loop through all dates since the repo's creation
          while [ "$first_commit_date" != "$current_date" ]; do
            # Get the LOC stats for the current day
            loc_stats=$(git log --since="$first_commit_date 00:00:00" --until="$first_commit_date 23:59:59" --pretty=tformat: --numstat \
            | awk '{ added += $1; deleted += $2; total += $1 - $2 } END { print added "," deleted "," total }')

            # If LOC data was found for the day, append it to the report
            if [ -n "$loc_stats" ]; then
              echo "$first_commit_date,$loc_stats" >> loc_report.csv
            fi

            # Move to the next day
            first_commit_date=$(date -I -d "$first_commit_date + 1 day")
          done

          # Display the generated report
          cat loc_report.csv

      - name: Stage and Commit LOC Report
        run: |
          git config user.name "vibhavchipsy"
          git config user.email "vibhavchipsy@gmail.com"
          git add loc_report.csv
          git commit -m "Daily LOC Report" || echo "Nothing to commit"
          git push
